### ISSUE TITLE
I can´t use the portlet

### ISSUE THREAD

**Issue by gabriel1979** [popupz/popups-portlet#1]
Hi! I have installed the portlet but I can use it. Appears the portlet in the portal admin but gives  error when I try tu add a new popup. 
I have downloaded and installed the portlet directly from the marketplace, the problem is that I can´t find the file ~/.gradle/gradle.properties to set the configuration into the portlet-popup folder. There is a more extensive file of support?

Thanks and best regards

**Comment by popupz** [comment]
You only need to create the  ~/.gradle/gradle.properties file if you want to build the project from source. If you installed the plugin from the marketplace it should "just work" or at least it does for me

What version of liferay are you using and are there any errors in the log ?

**Comment by gabriel1979** [comment]
Hi! 
The error in the log are the next:
P/1.1" 200 2100
192.168.41.104 - - [23/Aug/2013:07:32:31 +0000] "GET /group/control_panel/null HTTP/1.1" 404 9641
192.168.41.104 - - [23/Aug/2013:07:32:31 +0000] "GET /MarcoPolotheme-theme/images/messages/error.png HTTP/1.1" 200 701

MarcoPolotheme is my theme :-)

The version of LR is: Liferay Portal Community Edition 6.1.1 CE GA2.

The icon appears in the admin panel:
![image](https://f.cloud.github.com/assets/4611684/1014787/3c7aa032-0bc7-11e3-97c5-57a68faf8044.png)

but when I push to add a new popup, appears this:
![image](https://f.cloud.github.com/assets/4611684/1014792/79c379dc-0bc7-11e3-895f-61a3aac465b1.png)

Like I told you, I downloaded directly from the marketplace in the panel control and installed it. I didn´t do it anything else.

Thanks in advance!

**Comment by popupz** [comment]
That /group/control_panel/null error sounds like a problem with the configuration of your portal and not with this portlet

Are you getting the same error on other places as well ? Like when you click the back link in another portlet

I remember having this problem in the past as well. I think the problem has something to do with redirects not being allowed by liferay

Try looking at this these links for guidance : 

http://www.liferay.com/community/forums/-/message_boards/message/10920979
https://issues.liferay.com/browse/LPS-7948
